# Generated by Django 4.2.4 on 2023-10-20 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0017_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='nome_emprestado_anonimo',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='co_autor',
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 19, 57, 58, 676891)),
        ),
    ]
